2024-12-22 19:19:52,048 | WARNING | Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "C:\Users\Дом\PycharmProjects\pythonProject\Urban exercises\Module_12\tests_12_4.py", line 23, in test_run
    rnr = rwe.Runner(1001)
          ^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\PycharmProjects\pythonProject\Urban exercises\Module_12\rt_with_exceptions.py", line 6, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int
2024-12-22 19:19:52,050 | WARNING | Неверная скорость для Runner
Traceback (most recent call last):
  File "C:\Users\Дом\PycharmProjects\pythonProject\Urban exercises\Module_12\tests_12_4.py", line 11, in test_walk
    wlk = rwe.Runner('гуляка', -5)
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дом\PycharmProjects\pythonProject\Urban exercises\Module_12\rt_with_exceptions.py", line 11, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -5
